"""Add description column.

Revision ID: 3bed46c48b
Revises: 383a7e82c811
Create Date: 2014-04-04 11:34:18.678393

"""

# revision identifiers, used by Alembic.
revision = '3bed46c48b'
down_revision = '383a7e82c811'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('description', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'description')
    ### end Alembic commands ###
