"""Deleting user.username column.

Revision ID: 5327cf7c4399
Revises: 282315e9a00b
Create Date: 2014-04-07 18:06:23.778164

"""

# revision identifiers, used by Alembic.
revision = '5327cf7c4399'
down_revision = '282315e9a00b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', mysql.INTEGER(display_width=11), nullable=False))
    ### end Alembic commands ###
