"""Adding user.username column (correct way).

Revision ID: 57891d5ab53f
Revises: 5327cf7c4399
Create Date: 2014-04-07 18:06:55.638055

"""

# revision identifiers, used by Alembic.
revision = '57891d5ab53f'
down_revision = '5327cf7c4399'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    ### end Alembic commands ###
